### ISSUE TITLE
[Package] 누락

### ISSUE THREAD

**Issue by janguck** [rungjoo/korea_sentiment_style_transfer#1]
안녕하세요. 한국어의 대한 Style Transfer 연구를 공유해주셔서 감사합니다. 

실험 도중 pytorch_bert_embedding  이라는 Package가 import 할 수 없는데, pytorch_bert_embedding를 직접 작성하신건지 궁금합니다. 
(구글링을 했을 때 pytorch_bert_embedding 라는 패키지를 찾을 수 없어 문의드립니다.)

**Comment by rungjoo** [comment]
안녕하세요.
네 맞아요. 커스텀 코드인데.. 정확히 어떤 내용이 있었는지 저도 까먹었네요;;

저도 코드의 본 저장소를 잃어버려서 (전 회사에 코드가 있어서 ㅜㅜ) 업데이트를 하는 건 힘들 것 같아요..

코드를 봐서 유추해보려고 했는데 pytorch_bert_embedding가 어디에 쓰였는지 잘 모르겠네요..
한 번 pytorch_bert_embedding 줄을 주석처리하고 해보시겠어요?

**Comment by janguck** [comment]
안녕하세요 ^^.  답변 감사드립니다. 

train.py 부분의 
```bert_model, bert_tokenizer = bert_model_load('bert-base-multilingual-cased')``` 인데 
vocab과 tokenizer를 custom 하신 것 같습니다. 
transformer에 tokenizer와 vocab의 인덱스가 깨짐. 단어와 인덱스의 매칭이 서로 다름( custom <--> transformer)
이 부분때문에 질문 드렸습니다. 

감사합니다.

**Comment by rungjoo** [comment]
파일이나 폴더명을 보시면 아시겠지만.. 깃허브에 마구잡이식으로 올려둔거라 코드를 활용하기에 많이 부족해서 죄송하네요.
단순히 결과 확인용 느낌으로 쓰려면 다행히 inference 폴더에 결과들이 있긴 하네요.

(개인적으로) 스타일 변환에서 이 때 시도했던 방법은 발전이 필요한 방법이라 생각하네요 ㅎㅎ 하시려고하는 문제가 잘 해결되시길 바라겠습니다.
